edit makefile
meyer-lab/DrugResponseModel.jl pull request #328
Opened 2020-10-04 21:15 UTC by Farnazmdi

2020-10-04 21:21 UTC, Farnazmdi commented
@aarmey I checked this file and it should build. This error shows up in the build. I searched for it but couldn't find a solution for it. Could you please take a look at it?
![image](https://user-images.githubusercontent.com/34812750/95027348-a1658c00-064c-11eb-9dd8-7fad5f14212b.png)

2020-10-04 21:28 UTC, aarmey commented
Meaning you could get it to build on your account?

What are the rest of the changes here?

2020-10-04 21:31 UTC, Farnazmdi commented
Those changes are from before late August when I was editing the figure ylims, ... I don't think they mess with anything. 
I could run the code without error in the notebook. I honestly don't remember how to make `.jmd` file locally.
(I mean it builds as appose to one of the files that had errors in it and the figures were not being plotted in the pdf output)

2020-10-04 22:26 UTC, aarmey commented
Fixed! Looks like I needed to install something on the server.

2020-10-04 22:27 UTC, aarmey requested changes
Just one edit then this is good to merge.

2020-10-04 22:27 UTC, aarmey commented on makefile
> +all: combination.pdf
Think you want to revert this?

2020-10-04 22:28 UTC, Farnazmdi commented on makefile
> +all: combination.pdf
Thank you very much! I will revet it.

2020-10-04 22:47 UTC, Farnazmdi commented
![image](https://user-images.githubusercontent.com/34812750/95028896-c5c76580-0658-11eb-8869-e803eceeca86.png)
It still doesn't show any artifacts. It looks like it expects svg files as output. I can make figures instead of pdfs (by looking how you have done it in a mother repo). Please let me know if I should.

2020-10-04 23:00 UTC, aarmey commented
Just fixed that.

2020-10-05 01:03 UTC, Farnazmdi commented
Sorry, they are not showing up in the artifacts yet. However, it may not be our priority now; I can make the pdf files locally by running `make all`.
If you could approve, I will merge this and try to find a strategy for outputting the optimum combination in another branch.

2020-10-05 01:21 UTC, aarmey commented
Made one more attempt at getting them to work, but yes, you can merge regardless. If it doesn't work please open an issue and tag me.

2020-10-05 01:22 UTC, Farnazmdi commented
Thank you. I need your approval to be able to merge. I think I don't have permission.

2020-10-05 01:23 UTC, aarmey commented
Just made you an admin so you should be able to override.

2020-10-05 01:24 UTC, Farnazmdi commented
Thank you!

2020-10-05 01:24 UTC, merged