importing new data
meyer-lab/DrugResponseModel.jl pull request #507
Opened 2021-11-30 23:37 UTC by Farnazmdi

2021-12-01 03:30 UTC, aarmey requested changes

2021-12-01 03:30 UTC, aarmey commented on src/importData.jl
> +    for i = 1:96 # first set that have 191 data points
All this looping should be a table [reshape](https://dataframes.juliadata.org/stable/man/reshaping_and_pivoting/).

2021-12-01 03:30 UTC, aarmey commented on src/importData.jl
> +        d[:, i, 1] = savitzky_golay_filter(d[:, i, 1], 41, 3)
I'd suggest having a function that takes in a vector and does this filtering so that the filter settings are defined in one place.

2021-12-01 03:30 UTC, aarmey commented on src/importData.jl
> +function reorganize(gs, conditions)
What is going on here?!

2021-12-01 03:30 UTC, aarmey commented on src/importData.jl
> +function reorganize_data()
What is the purpose of this function?

2021-12-10 23:00 UTC, Farnazmdi commented
Here is just the data:
![image](https://user-images.githubusercontent.com/34812750/145651667-3cb1df20-4221-4818-babf-ebacdfb8f6f3.png)
![image](https://user-images.githubusercontent.com/34812750/145651702-b2f7dca2-d4d4-499a-8977-be0baa5a3a77.png)

Here is the total cell numbers:
![image](https://user-images.githubusercontent.com/34812750/145651741-ae4948ef-5fc2-4f3d-a4be-b1e5d6b6b1c9.png)
![image](https://user-images.githubusercontent.com/34812750/145651767-b9370902-cd2b-4c50-9840-86884157fd90.png)

I used Cyrillus's `figureCommon.jl` in the FCRegression repo, I hope it is alright with you. The figures look much better!

2021-12-10 23:43 UTC, aarmey commented
Great! Make sure the y-axes match?

2021-12-11 23:28 UTC, Farnazmdi commented
The axes are now from 0.0 to 2.0. 
I also edited that importing function. Now, given the name of the drug, we can call the g1, sg2, and the concentrations for all replicates of that drug.
I used 4 replicates of the vehicle as for the concentration 0 for all drugs, as Dr. Dane said the replicates are not exactly specific for each drug.
I believe this PR is ready to merge.

2021-12-12 03:35 UTC, aarmey reviewed
`data/AU565_round2and3_model_subset_level2.csv`... is this being used here?

2021-12-12 03:36 UTC, aarmey commented
One question, otherwise this looks good.

2021-12-12 05:12 UTC, Farnazmdi commented
Yes, that is the new data. It is used in the `import_data()` function which is called in other functions.

2021-12-12 15:59 UTC, aarmey requested changes
Ah, ok, I see that now.

In that case, what are the xlsx files for? I also found two places where the code should be simplified with loops.

2021-12-12 15:59 UTC, aarmey commented on src/figures/figure1.jl
> +    p1 = Eachdrug(tens[1, 1, :, :, 1], conditions[1], "G1")
All of these should be handled as a loop.

2021-12-12 15:59 UTC, aarmey commented on src/figures/figure1.jl
> +    p1 = Eachdrug(tens[1, 1, :, :, 1] .+ tens[2, 1, :, :, 1], conditions[1], "total")
Should be handled as a loop.

2021-12-12 18:09 UTC, Farnazmdi commented
Oh.. my bad.. I thought I had deleted the xlsx files. I will do it right away.

2021-12-13 03:49 UTC, aarmey approved these changes
Excellent!

2021-12-13 03:49 UTC, merged